version: "3"

services:
  db:
    image: mongo:latest
    volumes:
      - ./data:/data/db

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://db:27017/simple-chat
      - JWT_REFRESH_TOKEN_SECRET=secret
      - JWT_ACCESS_TOKEN_SECRET=secret

volumes:
  data:
